apiVersion: v1
kind: Pod
metadata:
  name: container2-pod
  labels:
    app: container2pod
spec:
  containers:
  - name: container2
    image: acnpublic.azurecr.io/workerlinux:v0.0.7
    ports:
    - containerPort: 443
      protocol: TCP
    - containerPort: 8080
      protocol: TCP
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "1Gi"
        cpu: "1"
  - name: alpine
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 36000; done"]
  nodeSelector:
    cx: vm2
  restartPolicy: Always